# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mmwave_streamer/mmwave_streamer.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmwave_streamer || ORIG_REF_NAME==mmwave_streamer} -quiet] -quiet

# IP: bd/mmwave_streamer/ip/mmwave_streamer_mmWaveStreamer_0_0/mmwave_streamer_mmWaveStreamer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmwave_streamer_mmWaveStreamer_0_0 || ORIG_REF_NAME==mmwave_streamer_mmWaveStreamer_0_0} -quiet] -quiet

# IP: bd/mmwave_streamer/ip/mmwave_streamer_points_RAM_0_0/mmwave_streamer_points_RAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmwave_streamer_points_RAM_0_0 || ORIG_REF_NAME==mmwave_streamer_points_RAM_0_0} -quiet] -quiet

# IP: bd/mmwave_streamer/ip/mmwave_streamer_data_parser_0_0/mmwave_streamer_data_parser_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmwave_streamer_data_parser_0_0 || ORIG_REF_NAME==mmwave_streamer_data_parser_0_0} -quiet] -quiet

# IP: bd/mmwave_streamer/ip/mmwave_streamer_UART_RX_0_0/mmwave_streamer_UART_RX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmwave_streamer_UART_RX_0_0 || ORIG_REF_NAME==mmwave_streamer_UART_RX_0_0} -quiet] -quiet

# IP: bd/mmwave_streamer/ip/mmwave_streamer_NOT_gate_0_0/mmwave_streamer_NOT_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmwave_streamer_NOT_gate_0_0 || ORIG_REF_NAME==mmwave_streamer_NOT_gate_0_0} -quiet] -quiet

# IP: bd/mmwave_streamer/ip/mmwave_streamer_stream_controller_0_0/mmwave_streamer_stream_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmwave_streamer_stream_controller_0_0 || ORIG_REF_NAME==mmwave_streamer_stream_controller_0_0} -quiet] -quiet

# XDC: /home/nm/mmwave-fpga-streamer/src/vhdl/mmwave-streamer/mmwave-streamer.gen/sources_1/bd/mmwave_streamer/mmwave_streamer_ooc.xdc
