#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Feb 24 10:25:36 CET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 245477d5cb874d669cf02dea9b0f5e16 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot sim_wrapper_func_synth xil_defaultlib.sim_wrapper -log elaborate.log"
xelab -wto 245477d5cb874d669cf02dea9b0f5e16 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot sim_wrapper_func_synth xil_defaultlib.sim_wrapper -log elaborate.log

