# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nm/mmwave-fpga-streamer/src/vhdl/mmwave-streamer/mmwave-streamer.srcs/sources_1/bd/sim/ip/sim_mmWaveStreamer_0_0/sim_mmWaveStreamer_0_0.xci
# IP: The module: 'sim_mmWaveStreamer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nm/mmwave-fpga-streamer/src/vhdl/mmwave-streamer/mmwave-streamer.gen/sources_1/bd/sim/ip/sim_mmWaveStreamer_0_0/constraints/mmWaveStreamer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sim_mmWaveStreamer_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/nm/mmwave-fpga-streamer/src/vhdl/mmwave-streamer/mmwave-streamer.srcs/sources_1/bd/sim/ip/sim_mmWaveStreamer_0_0/sim_mmWaveStreamer_0_0.xci
# IP: The module: 'sim_mmWaveStreamer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nm/mmwave-fpga-streamer/src/vhdl/mmwave-streamer/mmwave-streamer.gen/sources_1/bd/sim/ip/sim_mmWaveStreamer_0_0/constraints/mmWaveStreamer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sim_mmWaveStreamer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
